sudo: required
services:
 - docker

before_install:
 - gem install bundler
 - docker build -t anjubora/docker-react -f Dockerfile.dev .

script:
 - docker run anjubora/docker-react npm run test -- --coverage